//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Country
{
	isoName: string;
	name: string;
	alpha2Code: string;
	alpha3Code: string;
	numericCode: number;
}
export interface PagedResponse<T>
{
	records: T[];
	reference: number;
	pageSize: number;
	hasNext: boolean;
}
