//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Country } from './common-module';

export interface Elevation
{
	base: number;
	top: number;
}
export interface LiftInfrastructure
{
	aerialCablecarCount?: number;
	funicularCount?: number;
	gondolaLiftCount?: number;
	chairliftCount?: number;
	combinationLiftCount?: number;
	tbarLiftCount?: number;
	ropetowLiftCount?: number;
	carpetLiftCount?: number;
	heliSkiing?: boolean;
	catSkiing?: boolean;
}
export interface LiftLocation
{
	name: string;
	latitude: number;
	longitude: number;
	id: number;
}
export interface OperationInfo
{
	openHour?: Date;
	closeHour?: Date;
	seasonDuration?: string;
}
export interface SlopeInfo
{
	blueSlopesLength: number;
	redSlopesLength: number;
	blackSlopesLength: number;
	skiroutesLength: number;
}
export interface TicketPrices
{
	adults?: string;
	youth?: string;
	children?: string;
}
export interface SkiResort
{
	name: string;
	slug: string;
	rating?: number;
	website?: string;
	logoUrl?: string;
	externalUrl?: string;
	elevation?: Elevation;
	slopeInfo?: SlopeInfo;
	infrastructure?: LiftInfrastructure;
	operation?: OperationInfo;
	ticketPrices?: TicketPrices;
	country: Country;
	country2?: Country;
	lifts?: LiftLocation[];
	id: number;
}
export interface SkiResortListRequest
{
	country?: string;
	searchQuery?: string;
	reference: number;
	pageSize: number;
}
